#!/usr/bin/env python3
"""Regenerate variants.tsv: US -> UK/Canadian/Australian spellings.

Needs a built ESDB/SCOWL checkout (https://github.com/en-wl/wordlist, run
`make` there to get scowl.db). Only run when updating the list:

    python3 make_variants.py /path/to/wordlist/scowl.db > variants.tsv
"""
import sqlite3
import sys

REGIONS = {"GB": "B", "CA": "C", "AU": "D"}

# Every word valid in a region (same filter as `scowl word-list 60 <code> 1`).
REGION_WORDS = """
select distinct lower(word) from scowl_v0
 where size <= 60 and variant_level <= 1
   and spelling in ('_', ?) and region in (?, '')
"""

QUERY = """
select distinct lower(a.word), lower(b.word)
  from words_w_variant_info as a
  join words_w_variant_info as b using (group_id, pos)
 where a.spelling in ('_', 'A') and a.variant_level <= 1
   and b.spelling in ('_', ?) and b.variant_level <= 1
   and lower(a.word) != lower(b.word)
   and a.word not like '% %' and b.word not like '% %'
"""


def main():
    db = sqlite3.connect(sys.argv[1])
    print("# region\tus\tvariant\treplace  (generated by make_variants.py from "
          "ESDB/SCOWL, Copyright Kevin Atkinson; see README.md)")
    for region, code in REGIONS.items():
        valid = {w for (w,) in db.execute(REGION_WORDS, (code, region))}
        for us, variant in sorted(db.execute(QUERY, (code,)).fetchall()):
            if variant in valid:
                # replace=1: the US spelling is wrong there (color -> colour);
                # 0: both are words there (check / cheque), just add the variant.
                print(f"{region}\t{us}\t{variant}\t{0 if us in valid else 1}")


if __name__ == "__main__":
    main()
