#!/usr/bin/env python3
"""Renders Pebble's app icons from the stone definitions below.

Needs Pillow and cairosvg (pip install pillow cairosvg). Run from pebble/:
    python3 assets_source/images/app/generate.py
"""
import io
import os

import cairosvg
from PIL import Image

BACKGROUND = "#E3EFE8"
# (cx, cy, rx, ry, rotation, colour) on the 108x108 adaptive-icon grid.
STONES = [
    (54, 71, 26, 11, -4, "#2F5D50"),
    (53, 50.5, 19, 8.5, 5, "#4F8A76"),
    (55, 34, 12, 7, -7, "#86BBA5"),
]
RES = "android/app/src/main/res"
SERVICE_RES = "android/service/src/main/res"


def svg(size=108, background=None, colour=None, scale=1.0, shape=None):
    body = []
    if background:
        if shape == "circle":
            body.append(f'<circle cx="54" cy="54" r="54" fill="{background}"/>')
        elif shape == "squircle":
            body.append(f'<rect width="108" height="108" rx="24" fill="{background}"/>')
        else:
            body.append(f'<rect width="108" height="108" fill="{background}"/>')
    stones = "".join(
        f'<ellipse cx="{cx}" cy="{cy}" rx="{rx}" ry="{ry}" '
        f'transform="rotate({rot} {cx} {cy})" fill="{colour or fill}"/>'
        for cx, cy, rx, ry, rot, fill in STONES
    )
    body.append(
        f'<g transform="translate(54 54) scale({scale}) translate(-54 -54)">{stones}</g>'
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
        f'viewBox="0 0 108 108">{"".join(body)}</svg>'
    )


def png(markup, width, height=None):
    data = cairosvg.svg2png(
        bytestring=markup.encode(), output_width=width, output_height=height or width
    )
    return Image.open(io.BytesIO(data)).convert("RGBA")


def ellipse_path(cx, cy, rx, ry):
    return (
        f"M{cx - rx},{cy} A{rx},{ry} 0 1,0 {cx + rx},{cy} "
        f"A{rx},{ry} 0 1,0 {cx - rx},{cy} Z"
    )


def vector(colour=None, size_dp=108, scale=1.0, tint=None):
    groups = []
    for cx, cy, rx, ry, rot, fill in STONES:
        groups.append(
            f'    <group android:rotation="{rot}" android:pivotX="{cx}" android:pivotY="{cy}">\n'
            f'        <path\n'
            f'            android:fillColor="{colour or fill}"\n'
            f'            android:pathData="{ellipse_path(cx, cy, rx, ry)}" />\n'
            f'    </group>'
        )
    inner = "\n".join(groups)
    if scale != 1.0:
        inner = (
            f'    <group android:scaleX="{scale}" android:scaleY="{scale}" '
            f'android:pivotX="54" android:pivotY="54">\n{inner}\n    </group>'
        )
    tint_attr = f'\n    android:tint="{tint}"' if tint else ""
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by assets_source/images/app/generate.py -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size_dp}dp"\n'
        f'    android:height="{size_dp}dp"{tint_attr}\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        f"{inner}\n"
        "</vector>\n"
    )


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def main():
    # Adaptive icon layers.
    write(f"{RES}/drawable/ic_launcher_foreground.xml", vector())
    write(f"{RES}/drawable/ic_launcher_foreground_tv.xml", vector(scale=0.8))
    write(f"{RES}/drawable/ic_launcher_monochrome.xml", vector(colour="#FF000000"))
    write(
        f"{RES}/values/ic_launcher_background.xml",
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        f'    <color name="ic_launcher_background">{BACKGROUND}</color>\n'
        "</resources>\n",
    )
    # Notification and quick-settings tile icons: white silhouettes. The
    # stones are scaled up since these have no safe-zone padding.
    for name in ("ic_service", "ic"):
        write(
            f"{SERVICE_RES}/drawable/{name}.xml",
            vector(colour="#FFFFFFFF", size_dp=24, scale=1.5),
        )

    # Legacy launcher icons (API < 26).
    for density, size in {
        "mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192,
    }.items():
        png(svg(background=BACKGROUND, shape="squircle", scale=1.15), size).save(
            f"{RES}/mipmap-{density}/ic_launcher.webp", lossless=True
        )
        png(svg(background=BACKGROUND, shape="circle", scale=1.1), size).save(
            f"{RES}/mipmap-{density}/ic_launcher_round.webp", lossless=True
        )
    for density, size in {
        "mdpi": 80, "hdpi": 120, "xhdpi": 160, "xxhdpi": 240, "xxxhdpi": 320,
    }.items():
        png(svg(background=BACKGROUND, scale=0.9), size).save(
            f"{RES}/mipmap-television-{density}/ic_launcher.webp", lossless=True
        )

    # Android TV banner (320x180): stones and the name.
    stones = "".join(
        f'<ellipse cx="{cx}" cy="{cy}" rx="{rx}" ry="{ry}" '
        f'transform="rotate({rot} {cx} {cy})" fill="{fill}"/>'
        for cx, cy, rx, ry, rot, fill in STONES
    )
    banner = (
        '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180" viewBox="0 0 320 180">'
        f'<rect width="320" height="180" fill="{BACKGROUND}"/>'
        f'<g transform="translate(-18 2) scale(1.6)">{stones}</g>'
        '<text x="136" y="106" font-family="DejaVu Sans, sans-serif" font-size="44" '
        'font-weight="bold" fill="#2F5D50">Pebble</text></svg>'
    )
    Image.open(io.BytesIO(cairosvg.svg2png(bytestring=banner.encode()))).save(
        f"{RES}/mipmap-xhdpi/ic_banner.png"
    )

    # In-app glyph (About page, Windows icon source): transparent, cropped.
    glyph = png(svg(), 1080)
    box = glyph.getbbox()
    side = max(box[2] - box[0], box[3] - box[1])
    pad = side // 12
    square = Image.new("RGBA", (side + 2 * pad,) * 2)
    square.paste(
        glyph.crop(box),
        (pad + (side - (box[2] - box[0])) // 2, pad + (side - (box[3] - box[1])) // 2),
    )
    square.resize((550, 550), Image.LANCZOS).save("assets/images/icon.png")

    # windows/runner/resources/app_icon.ico and the tray icons come from
    # tool/generate_status_icons.dart (run it after this script).
    ico = png(svg(background=BACKGROUND, shape="squircle", scale=1.15), 256)
    sizes = [(s, s) for s in (16, 24, 32, 48, 64, 128, 256)]
    ico.save("assets/images/icon.ico", sizes=sizes)


if __name__ == "__main__":
    main()
